name: 'recursoshumanos-api-service'

networks:
  default:
    name: recursoshumanos
    external: false

services:

  minio-rh-ingt:
    image: minio/minio:latest
    container_name: minio-rh-ingt
    restart: no
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./data:/rh_ingt_minio_data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }    # check if Minio is alive
        minio $0 "$@" --quiet & echo $! > /tmp/minio.pid                   # start Minio in the background
        while ! isAlive; do sleep 0.1; done                                # wait until Minio is alive
        mc alias set minio http://127.0.0.1:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} # setup Minio client
        mc mb minio/${MINIO_BUCKET_NAME}|| true                            # create a test bucket
        mc anonymous set public minio/${MINIO_BUCKET_NAME}                 # make the test bucket public
        kill -s INT $(cat /tmp/minio.pid) && rm /tmp/minio.pid             # stop Minio
        while isAlive; do sleep 0.1; done                                  # wait until Minio is stopped
        exec minio $0 "$@"
      '

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    volumes:
      - postgres-data-17:/var/lib/postgresql/data
    restart: unless-stopped
  recursoshumanos-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recursoshumanos-service
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=${SERVICE_PORT}
      - SERVICE_NAME=recursoshumanos-service
      - SPRING_ACTIVE_PROFILE=${SERVICE_PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ENABLE_SWAGGER=${ENABLE_SWAGGER}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

volumes:
  postgres-data-17:
    driver: local


