/* Originally generated by iGRP Studio. The generator's "DO NOT MODIFY" banner was removed
 * on 2026-08-20: the operator ruled that this project maintains the backend directly and
 * does not regenerate from IGRP Studio. Leaving it above a hand-edited file told the next
 * reader the opposite of the truth.
 *
 * MANUALLY EDITED - Phase 93 (INT-01): added the fiscalYear lifecycle callback below.
 */

package cv.igrp.RH_Service.sigdi.infrastructure.persistence.entity;

import cv.igrp.RH_Service.shared.config.AuditEntity;
import cv.igrp.framework.stereotype.IgrpEntity;
import jakarta.persistence.*;
import lombok.*;
import java.util.UUID;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

import org.hibernate.envers.Audited;

@Audited
@Getter
@Setter
@IgrpEntity
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "t_tactical_activities")
public class TacticalActivitiesEntity extends AuditEntity {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private UUID id;


    @NotNull(message = "strategicGoalId is mandatory")
    @Column(name="strategic_goal_id", nullable = false)
    private UUID strategicGoalId;


    @Column(name="institution_id")
    private UUID institutionId;


    @Column(name="organic_unit_id")
    private UUID organicUnitId;


    @Column(name="title")
    private String title;


    @Lob
    @Column(name="description_what", columnDefinition="TEXT")
    private String descriptionWhat;


    @Lob
    @Column(name="justification_why", columnDefinition="TEXT")
    private String justificationWhy;


    @Column(name="location_where")
    private String locationWhere;


    @Column(name="responsible_who")
    private UUID responsibleWho;


    @Lob
    @Column(name="methodology_how", columnDefinition="TEXT")
    private String methodologyHow;


    @Column(name="start_date")
    private LocalDate startDate;


    @Column(name="end_date")
    private LocalDate endDate;


    @Column(name="budget_estimated")
    private BigDecimal budgetEstimated;


    @Column(name="budget_committed")
    private BigDecimal budgetCommitted;


    @Column(name="budget_liquidated")
    private BigDecimal budgetLiquidated;


    @Column(name="budget_paid")
    private BigDecimal budgetPaid;


    @Column(name="fiscal_year")
    private Integer fiscalYear;


    @Column(name="economic_classifier")
    private String economicClassifier;


    @Column(name="status")
    private String status;


    @Column(name="paa_level", length = 50)
    private String paaLevel = "UNIT_LEVEL";


    @Column(name="acceptance_status")
    private String acceptanceStatus;


    @Column(name="version")
    private Integer version;


  @OneToMany(mappedBy = "activityId", fetch = FetchType.LAZY, cascade = { CascadeType.ALL })
private List<KeyResultsEntity> keyResults = new ArrayList<>();


  @OneToMany(mappedBy = "activityId", fetch = FetchType.LAZY, cascade = { CascadeType.ALL })
private List<TaticalActivityHistoryEntity> historicals = new ArrayList<>();


  @OneToMany(mappedBy = "activityId", fetch = FetchType.LAZY, cascade = { CascadeType.ALL })
private List<ChangeRequestEntity> changeRequests = new ArrayList<>();

    /**
     * Derives {@code fiscal_year} from {@code start_date} on every write.
     *
     * <p>Scenario simulation loads activities exclusively through
     * {@code findAllByFiscalYear} / {@code findAllByFiscalYearAndOrganicUnitId}. Until this
     * callback existed, no production command ever wrote the column: every activity created
     * through the application carried {@code fiscal_year = null} for its whole life, so every
     * simulation returned zero activities regardless of how much real data existed. That was
     * ACH-C-02, the second Critical finding of the v22.0 test run.
     *
     * <p>This lives on the entity rather than in TacticalActivityMapper.toEntity() on purpose.
     * The mapper is not the only write path: CreateTacticalActivityCommandHandler,
     * ChangeStatusTacticalActivityCommandHandler and TacitAcceptanceScheduler all reach
     * TacticalActivitiesEntityRepository directly, bypassing it. A JPA lifecycle callback is
     * the one point every write passes through, so a future handler that also bypasses the
     * mapper cannot reintroduce the defect by omission.
     *
     * <p>The value is always recomputed rather than filled in only when null: start_date is the
     * single source of truth, so moving an activity into another year must move its fiscal year
     * with it, otherwise the simulation would keep finding it under the old one. Cabo Verde's
     * fiscal year is the calendar year, so the start date's year is the fiscal year.
     *
     * <p>A null start_date leaves fiscal_year untouched -- there is nothing to derive from, and
     * blanking a previously correct value would be worse than leaving it.
     */
    @PrePersist
    @PreUpdate
    void deriveFiscalYearFromStartDate() {
        if (startDate != null) {
            fiscalYear = startDate.getYear();
        }
    }
}
