// Hand-written, NOT generated by iGRP Studio: there is no manifest for this DTO under
// .igrpstudio/sigdi/dto/. Same precedent as IncoherentLinkDTO (wave 4 of Phase 130),
// FormGenerationRevertSkippedItemDTO (Phase 120) and the three read DTOs of Phase 119.
//
// THE PUT RESPONSE CHANGES SHAPE AND THE GET RESPONSE DOES NOT, AND THE ASYMMETRY IS DELIBERATE.
// Until wave 5 of Phase 130 both GET and PUT /admin/bsc-perspectives returned a bare array of
// BscPerspectiveItemDTO. The PUT now returns this envelope; the GET is untouched.
//
//   GET   /admin/bsc-perspectives   bare array                          UNCHANGED
//   PUT   /admin/bsc-perspectives   { perspectives, incoherentLinks }   NEW
//
// Why: READING the configuration does not change it, so the GET has nothing to warn about --
// there is no "this reading just made a stored link incoherent". The warning only exists as a
// consequence of a WRITE, so it belongs on the response to the write. And changing the GET would
// reach fetchBscPerspectives and every consumer of useBscPerspectives in the sibling frontend,
// including the PERSPECTIVE_FALLBACK that FIX-02 measured -- scope FIX-10 does not ask for.
//
// The PUT's consumers were counted before the shape was changed: four call sites, of which
// exactly ONE reads the shape (updateBscPerspectives in
// src/app/(myapp)/functions/bsc-perspectives.ts). That measurement is what makes this a cheap
// change rather than a risky one, and it is why it is written down.
package cv.igrp.RH_Service.sigdi.application.dto;

import cv.igrp.framework.stereotype.IgrpDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@IgrpDTO
public class BscPerspectivesUpdateResponseDTO {

  /**
   * Whether the coherence reading behind {@link #incoherentLinks} actually happened.
   *
   * <p>Rule 5 of the project {@code CLAUDE.md} forbids an indistinguishable absence, and its
   * corollary forbids presenting one as legitimate unless its cause has been DISCRIMINATED rather
   * than presumed. An empty list of warnings is exactly such an absence: it can mean "the
   * configuration was saved and nothing became incoherent" or "no reading was possible because
   * there is no active institutional identity". The two have different remedies -- none, and
   * create an identity -- so they are two states here and not one.
   */
  public enum CoherenceCheck {
    /** The stored links were read. {@code incoherentLinks} is the complete answer, empty or not. */
    EVALUATED,

    /**
     * There is no active institutional identity, so there was nothing to read the links of. The
     * perspectives WERE saved -- this says nothing about the write, only about the warning.
     */
    NOT_EVALUATED_NO_ACTIVE_IDENTITY
  }

  /** The four saved perspectives, in the exact shape the response already had, sorted by position. */
  private List<BscPerspectiveItemDTO> perspectives;

  /**
   * Which state {@link #incoherentLinks} is in. Never null.
   */
  private CoherenceCheck coherenceCheck;

  /**
   * Every stored link that the rule in force would no longer allow to be created, AFTER this
   * save -- FIX-10 / A-126-05.
   *
   * <p>Null, and never an empty list, when {@link #coherenceCheck} is
   * {@code NOT_EVALUATED_NO_ACTIVE_IDENTITY}: an empty list is an answer, and no answer is not one.
   *
   * <p>This travels on a 200, next to a configuration that WAS saved. Decision 2 of
   * {@code 130-CONTEXT.md} is warn and save: reordering perspectives is a legitimate
   * configuration whose consequence appears afterwards, so it is warned about and never refused.
   */
  private List<IncoherentLinkDTO> incoherentLinks;
}
