// Hand-written, NOT generated by iGRP Studio: there is no manifest for this DTO under
// .igrpstudio/sigdi/dto/. Same precedent as FormGenerationRevertSkippedItemDTO (Phase 120) and
// the three read DTOs of Phase 119.
//
// THIS DTO IS CONSUMED BY TWO ENTRY POINTS, AND ITS VOCABULARY IS PRIVATE TO NEITHER OF THEM.
//   1. Updating a strategic goal (FIX-09 / A-124-02, wave 4 of Phase 130): changing a goal's
//      perspective can leave an already-stored link in a state the rule in force would no longer
//      allow to be created. That change WARNS AND SAVES -- decision 2 of 130-CONTEXT.md -- and
//      this is the shape of the warning.
//   2. Updating the BSC perspective order (FIX-10 / A-126-05, wave 5): reordering perspectives
//      can do exactly the same thing to links nobody touched. That handler crosses the PERSP-03
//      isolation BY READING ONLY, and reports through this same DTO.
//
// Because two callers share it, no field may be named or shaped for the convenience of only one
// of them, and the {@code reason} enum below is where wave 5 adds its own value.
package cv.igrp.RH_Service.sigdi.application.dto;

import cv.igrp.framework.stereotype.IgrpDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@IgrpDTO
public class IncoherentLinkDTO {

  /**
   * Why a single stored link is reported as one the rule in force would no longer allow to be
   * created. The field exists from day one, with more than one value, because rule 5 of the
   * project CLAUDE.md forbids an indistinguishable warning: a caller that received a flat list
   * with no cause attached could not tell a link broken by perspective ORDER from a link broken
   * by anything else, and would have to guess. Wave 5 of Phase 130 adds {@code GOAL_CANCELLED}
   * here; that is the whole reason this enum is not collapsed into a boolean.
   *
   * <p><b>Divergence from what wave 4 predicted here, written and not silently applied.</b> The
   * sentence above used to announce TWO new values, {@code SOURCE_GOAL_CANCELLED} and
   * {@code TARGET_GOAL_CANCELLED}. Wave 5 added ONE, {@code GOAL_CANCELLED}, and the reason is the
   * criterion this enum already uses everywhere else: two causes stay apart when their REMEDIES
   * differ ("re-point the link" versus "configure the perspective"). A cancelled source and a
   * cancelled target have the SAME remedy, and WHICH end is cancelled is already carried without
   * ambiguity by {@link #reasonDesc} and by the {@code sourceGoalTitle} / {@code targetGoalTitle}
   * fields. Splitting on an axis the reader does not act on would have added a distinction that
   * costs a caller a branch and buys nothing.
   */
  public enum Reason {
    /**
     * The cause-effect direction is inverted: the source perspective sits at a display order
     * LOWER than the target's. This is the pair {@code CreateStrategyMapLinkCommandHandler}
     * refuses with "Ligação inválida: a perspetiva de origem não pode estar numa ordem inferior
     * à da perspetiva de destino no fluxo causa-efeito do BSC".
     */
    CAUSE_EFFECT_ORDER_INVERTED,

    /**
     * One of the two perspectives has no row in {@code t_bsc_perspective_config}, so its display
     * order cannot be read at all and the cause-effect rule cannot be evaluated.
     * {@code CreateStrategyMapLinkCommandHandler} refuses this pair too ("Perspetiva não
     * configurada: ..."), which is why {@code StrategyLinkCoherencePolicy} must report it -- the
     * mirror test fixes that the two sides agree. It is a SEPARATE value and not folded into
     * {@code CAUSE_EFFECT_ORDER_INVERTED} because the two causes need different remedies: one is
     * fixed by re-pointing the link, the other by configuring the perspective.
     */
    PERSPECTIVE_NOT_CONFIGURED,

    /**
     * At least one of the two goals the link joins is cancelled ({@code Estado.I}). This is the
     * pair {@code CreateStrategyMapLinkCommandHandler} refuses from wave 5 of Phase 130 onwards
     * (FIX-10 / A-125-01), with "Não é possível ligar: o objetivo de origem|destino está
     * cancelado".
     *
     * <p><b>This value reports; it never removes.</b> The two links stored in this environment
     * both join cancelled goals, and they are the material of the finding: the guard in the
     * create handler is for CREATING, and this reason exists so an already-stored link can be
     * NAMED without being touched.
     */
    GOAL_CANCELLED
  }

  private UUID linkId;

  private UUID sourceGoalId;

  private String sourceGoalTitle;

  private String sourcePerspective;

  /** Null when the source perspective has no configured row -- see {@link Reason}. */
  private Integer sourcePerspectiveOrder;

  private UUID targetGoalId;

  private String targetGoalTitle;

  private String targetPerspective;

  /** Null when the target perspective has no configured row -- see {@link Reason}. */
  private Integer targetPerspectiveOrder;

  /**
   * The FIRST cause found, in the same order the create handler evaluates its guards: the status
   * clause runs before the perspective clause, so a link that violates both reports
   * {@code GOAL_CANCELLED} here. Kept as a single value because wave 4's consumers already read
   * it; {@link #reasons} is the complete list and always contains this one.
   */
  private Reason reason;

  /**
   * EVERY cause this link violates, and not only the first -- added by wave 5 of Phase 130.
   *
   * <p>A link can violate more than one clause at once: the two stored in this environment join
   * cancelled goals, and reordering perspectives can additionally invert their cause-effect
   * direction. Reporting only the first would be a warning that hides half of its own cause, and
   * the reader would fix one thing and see the link reported again for another. Never empty, and
   * its first element is always {@link #reason}.
   */
  private List<Reason> reasons;

  /**
   * Human-readable PT-PT sentence covering ALL of {@link #reasons}, not only {@link #reason}. It
   * travels with the code, following the
   * same precedent as {@code FormGenerationRevertSkippedItemDTO#reasonDescription} and
   * {@code StategicGoalResponseDTO#statusDesc}: the server owns the wording, so no caller has to
   * keep a translation table of its own in sync with this enum.
   */
  private String reasonDesc;
}
