/* Originally generated by iGRP Studio. The generator's "DO NOT MODIFY" banner was removed
 * on 2026-08-20: the operator ruled that this project maintains the backend directly and
 * does not regenerate from IGRP Studio (see .planning/phases/92-.../92-CONTEXT.md). Leaving
 * the banner above a hand-edited file told the next reader the opposite of the truth
 * (92-REVIEW.md IN-02).
 *
 * MANUALLY EDITED — Phase 92 (OKR-01): fixed a field-name typo on the value field
 * (it was missing its "e") and removed the unintended required-evidence constraint on
 * evidenceUrl, which the domain has always treated as optional. Regenerating this file
 * via IGRP Studio would reintroduce both defects.
 */

package cv.igrp.RH_Service.sigdi.application.dto;

import cv.igrp.framework.stereotype.IgrpDTO;
import jakarta.validation.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor


@IgrpDTO
public class KeyResultCheckinRequestDTO  {

  @NotNull(message = "The field <valueAdded> is required")

  private BigDecimal valueAdded ;
  @NotBlank(message = "The field <comment> is required")

  private String comment ;

  private String evidenceUrl ;

}