# General
spring.config.import=optional:file:.env[.properties]
spring.jpa.open-in-view=false

spring.application.name=RecursosHumanos
# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:development}