# ---------------------------------------------
# Development
# ---------------------------------------------
# TODO: remove after next successful deploy (fixes V17 checksum mismatch)
spring.flyway.repair-on-migrate=true
