# General
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT}

# Eureka Configurations
eureka.client.enabled=false
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
# Spring Cloud Kubernetes
spring.cloud.kubernetes.discovery.enabled=${KUBERNETES_DISCOVERY_ENABLED:false}

# Logging Levels
#sets the baseline logging level for the entire application
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
#targets the web layer, allowing control over HTTP request/response logs
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:INFO}
#applies to our application-specific logic, providing detailed logging where needed
logging.level.cv.igrp.RH-Service=${LOGGING_LEVEL_APP:INFO}

# Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Entity Revision
# Track entity names modified during a revision
#spring.jpa.properties.org.hibernate.envers.track_entities_changed_in_revision=true
# Enable withModifiedFlag globally
#spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true
# Set schema and catalog for audit tables
#spring.jpa.properties.org.hibernate.envers.default_schema=audit_schema
# Spring Data REST
spring.data.rest.detection-strategy=annotated

# Authentication
auth.jwt.issuer=${AUTH_JWT_ISSUER}

# Swagger Documentation
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.docExpansion=none


# Minio
igrp.minio.url=${MINIO_URL}
igrp.minio.port=${MINIO_PORT}
igrp.minio.security=${MINIO_SECURITY}
igrp.minio.access-key=${MINIO_ACCESS_KEY}
igrp.minio.secret-key=${MINIO_SECRET_KEY}
igrp.minio.bucket-name=${MINIO_BUCKET_NAME}
igrp.minio.url-expiration-time=${MINIO_PRESIGNED_URL_EXPIRATION_TIME}
# Minio Logging
logging.level.io.minio=DEBUG
logging.level.cv.igrp.platform.filemanager=DEBUG
