/* Originally generated by iGRP Studio. The generator's "DO NOT MODIFY" banner was removed
 * on 2026-08-20: the operator ruled that this project maintains the backend directly and does
 * not regenerate from IGRP Studio. Leaving the banner above a hand-edited file told the next
 * reader the opposite of the truth (same reasoning already applied to
 * application/dto/KeyResultCheckinRequestDTO.java).
 *
 * MANUALLY EDITED - Phase 94 (SIA-01 / ACH-A-04): added
 * POST siadap/evaluations/{id}/merit-rating, the first caller of
 * SiadapEvaluation.assignMeritRating(). Regenerating this file via IGRP Studio would drop the
 * endpoint and leave merit-rating corrections back where they were: direct SQL against the
 * database.
 *
 * MANUALLY EDITED - Phase 104 (SIA-05, decision D-01): added
 * GET siadap/me/cca-status, the only read point for CCA (Conselho Coordenador da Avaliacao)
 * membership. Regenerating this file via IGRP Studio would drop the endpoint and leave the
 * frontend with no way to decide who the CCA screen should be shown to.
 */

package cv.igrp.RH_Service.sigdi.interfaces.rest;

import cv.igrp.framework.stereotype.IgrpController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.HttpStatus;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.validation.Valid;

import cv.igrp.framework.core.domain.QueryBus;
import cv.igrp.RH_Service.sigdi.application.queries.*;
import cv.igrp.framework.core.domain.CommandBus;
import cv.igrp.RH_Service.sigdi.application.commands.*;
import cv.igrp.RH_Service.sigdi.application.dto.CloseEvaluationsRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.CloseEvaluationsResponseDTO;
import cv.igrp.RH_Service.sigdi.application.dto.QUARPreviewResponseDTO;
import cv.igrp.RH_Service.sigdi.application.dto.QuotaValidationResponseDTO;
import cv.igrp.RH_Service.sigdi.application.dto.SiadapCcaStatusDTO;
import cv.igrp.RH_Service.sigdi.application.dto.WrapperSiadapEvaluationListDTO;
import cv.igrp.RH_Service.sigdi.application.dto.SiadapEvaluationDTO;
import cv.igrp.RH_Service.sigdi.application.dto.CreateSiadapEvaluationRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.ContractualizeObjectivesRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.EvaluateCompetenciesRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.RecordObjectiveAchievementRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.SubmitSelfEvaluationRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.FinalizeEvaluationRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.AssignMeritRatingRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.IndividualObjectiveDTO;
import cv.igrp.RH_Service.sigdi.application.dto.CompetencyItemDTO;
import cv.igrp.RH_Service.sigdi.application.dto.SiadapInterimFeedbackDTO;
import cv.igrp.RH_Service.sigdi.application.dto.NegotiateSiadapObjectivesRequestDTO;
import cv.igrp.RH_Service.sigdi.application.dto.NegotiateObjectiveRevisionRequestDTO;
import java.util.List;

@IgrpController
@RestController
@RequestMapping(path = "api/v1/compliance")
@Tag(
    name = "SIGDI-Compliance",
    description = "QUAR generation, SIADAP evaluations and quota validation"
)
public class ComplianceController {

  private final QueryBus queryBus;
  private final CommandBus commandBus;

  public ComplianceController(QueryBus queryBus, CommandBus commandBus) {
    this.queryBus = queryBus;
    this.commandBus = commandBus;
  }

  @GetMapping(value = "quar/preview")
  @Operation(
    summary = "Get QUAR preview",
    description = "Retorna os dados do QUAR em JSON para pré-visualização.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = QUARPreviewResponseDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<QUARPreviewResponseDTO> getQUARPreview(
    @RequestParam(value = "year") Integer year,
    @RequestParam(value = "organicUnitId", required = false) String organicUnitId)
  {
    final var query = new GetQUARPreviewQuery(year, organicUnitId);
    return queryBus.handle(query);
  }

  @GetMapping(value = "quar/export")
  @Operation(
    summary = "Export QUAR",
    description = "Gera e descarrega o QUAR no formato solicitado (PDF ou EXCEL).",
    responses = {
      @ApiResponse(
          responseCode = "200",
          description = "Binary file content"
      )
    }
  )
  public ResponseEntity<byte[]> exportQUAR(
    @RequestParam(value = "year") Integer year,
    @RequestParam(value = "format", required = false, defaultValue = "PDF") String format,
    @RequestParam(value = "organicUnitId", required = false) String organicUnitId,
    @RequestParam(value = "force", required = false, defaultValue = "false") Boolean force)
  {
    final var query = new GetQUARExportQuery(year, format, organicUnitId, force);
    return queryBus.handle(query);
  }

  @GetMapping(value = "siadap/evaluations")
  @Operation(
    summary = "List SIADAP evaluations",
    description = "Lista avaliações SIADAP de uma unidade orgânica.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = WrapperSiadapEvaluationListDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<WrapperSiadapEvaluationListDTO> listEvaluations(
    @RequestParam(value = "year") Integer year,
    @RequestParam(value = "organicUnitId", required = false) String organicUnitId,
    @RequestParam(value = "status", required = false) String status,
    @RequestParam(value = "pageNumber", required = false, defaultValue = "0") String pageNumber,
    @RequestParam(value = "pageSize",   required = false, defaultValue = "20") String pageSize)
  {
    final var query = new ListSiadapEvaluationsQuery(year, organicUnitId, status, pageNumber, pageSize);
    return queryBus.handle(query);
  }

  @GetMapping(value = "siadap/quota-validation")
  @Operation(
    summary = "Validate SIADAP quotas",
    description = "Valida o cumprimento das quotas de mérito por unidade.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = QuotaValidationResponseDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<QuotaValidationResponseDTO> quotaValidation(
    @RequestParam(value = "year") Integer year)
  {
    final var query = new GetQuotaValidationQuery(year);
    return queryBus.handle(query);
  }

  @GetMapping(value = "siadap/me/cca-status")
  @Operation(
    summary = "Get current user's CCA membership status",
    description = "Indica se o utilizador atual pertence ao Conselho Coordenador da Avaliação (CCA).",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapCcaStatusDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapCcaStatusDTO> ccaStatus()
  {
    final var query = new GetSiadapCcaStatusQuery();
    return queryBus.handle(query);
  }

  @PostMapping(value = "siadap/evaluations/close")
  @Operation(
    summary = "Close evaluations",
    description = "Fecha as avaliações de uma unidade orgânica. Valida quotas antes de executar.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = CloseEvaluationsResponseDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<CloseEvaluationsResponseDTO> closeEvaluations(
    @Valid @RequestBody CloseEvaluationsRequestDTO closeEvaluationsRequest)
  {
    final var command = new CloseEvaluationsCommand(closeEvaluationsRequest);
    return commandBus.send(command);
  }

  @GetMapping(value = "siadap/export")
  @Operation(
    summary = "Export SIADAP evaluations",
    description = "Exporta avaliações SIADAP em lote (EXCEL ou PDF_BATCH).",
    responses = {
      @ApiResponse(
          responseCode = "200",
          description = "Binary file content"
      )
    }
  )
  public ResponseEntity<byte[]> exportSiadap(
    @RequestParam(value = "year") Integer year,
    @RequestParam(value = "organicUnitId", required = false) String organicUnitId,
    @RequestParam(value = "format", required = false, defaultValue = "EXCEL") String format)
  {
    final var query = new GetSiadapExportQuery(year, organicUnitId, format);
    return queryBus.handle(query);
  }

  @PostMapping(value = "siadap/evaluations")
  @Operation(
    summary = "Create SIADAP evaluation",
    description = "Cria uma nova avaliação no início do ciclo (fase OPEN).",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> createEvaluation(
    @Valid @RequestBody CreateSiadapEvaluationRequestDTO request)
  {
    final var command = new CreateSiadapEvaluationCommand(request);
    return commandBus.send(command);
  }

  @GetMapping(value = "siadap/evaluations/{id}")
  @Operation(
    summary = "Get SIADAP evaluation details",
    description = "Retorna os detalhes completos de uma avaliação (fases, objetivos, competências).",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> getEvaluationDetail(
    @PathVariable("id") String id)
  {
    final var query = new GetEvaluationDetailQuery(id);
    return queryBus.handle(query);
  }

  @PostMapping(value = "siadap/evaluations/{id}/objectives")
  @Operation(
    summary = "Contractualize objectives",
    description = "Define os objetivos individuais para a avaliação.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> contractualizeObjectives(
    @PathVariable("id") String id,
    @Valid @RequestBody List<IndividualObjectiveDTO> objectives)
  {
    final var request = new ContractualizeObjectivesRequestDTO(id, objectives);
    final var command = new ContractualizeObjectivesCommand(request);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/objectives/accept")
  @Operation(
    summary = "Accept proposed objectives",
    description = "Avaliado aceita os objetivos propostos pelo avaliador.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> acceptSiadapObjectives(
    @PathVariable("id") String id)
  {
    return commandBus.send(new AcceptSiadapObjectivesCommand(id));
  }

  @PostMapping(value = "siadap/evaluations/{id}/objectives/negotiate")
  @Operation(
    summary = "Negotiate proposed objectives",
    description = "Avaliado solicita negociação dos objetivos propostos.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> negotiateSiadapObjectives(
    @PathVariable("id") String id,
    @Valid @RequestBody NegotiateSiadapObjectivesRequestDTO body)
  {
    return commandBus.send(new NegotiateSiadapObjectivesCommand(id, body));
  }

  @PostMapping(value = "siadap/evaluations/{id}/competencies")
  @Operation(
    summary = "Evaluate competencies",
    description = "Define e avalia as competências do colaborador.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> evaluateCompetencies(
    @PathVariable("id") String id,
    @Valid @RequestBody List<CompetencyItemDTO> competencies)
  {
    final var request = new EvaluateCompetenciesRequestDTO(id, competencies);
    final var command = new EvaluateCompetenciesCommand(request);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/objectives/achievements")
  @Operation(
    summary = "Record objective achievement",
    description = "Regista o valor atingido e pontuação de um objetivo específico.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> recordObjectiveAchievement(
    @PathVariable("id") String id,
    @Valid @RequestBody RecordObjectiveAchievementRequestDTO request)
  {
    request.setEvaluationId(id);
    final var command = new RecordObjectiveAchievementCommand(request);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/self-evaluation")
  @Operation(
    summary = "Submit self-evaluation",
    description = "Colaborador submete a sua autoavaliação.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> submitSelfEvaluation(
    @PathVariable("id") String id,
    @Valid @RequestBody SubmitSelfEvaluationRequestDTO request)
  {
    request.setEvaluationId(id);
    final var command = new SubmitSelfEvaluationCommand(request);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/finalize")
  @Operation(
    summary = "Finalize evaluation",
    description = "Calcula notas finais e avança a avaliação para harmonização.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> finalizeEvaluation(
    @PathVariable("id") String id)
  {
    final var request = new FinalizeEvaluationRequestDTO(id);
    final var command = new FinalizeEvaluationCommand(request);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/merit-rating")
  @Operation(
    summary = "Assign merit rating",
    description = "Atribui ou corrige a menção de mérito de uma avaliação já finalizada "
        + "(fases Harmonização ou Encerrado). Valores aceites no campo meritRating: "
        + "INADEQUATE, REGULAR, GOOD, VERY_GOOD, EXCELLENT.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapEvaluationDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapEvaluationDTO> assignMeritRating(
    @PathVariable("id") String id,
    @Valid @RequestBody AssignMeritRatingRequestDTO body)
  {
    return commandBus.send(new AssignMeritRatingCommand(id, body));
  }

  @GetMapping(value = "siadap/evaluations/{id}/interim-feedback")
  @Operation(
    summary = "Get SIADAP interim feedback",
    description = "Retorna os dados da ficha de feedback intercalar de uma avaliação.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapInterimFeedbackDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapInterimFeedbackDTO> getInterimFeedback(
    @PathVariable("id") String id)
  {
    final var query = new GetSiadapInterimFeedbackQuery(id);
    return queryBus.handle(query);
  }

  @PostMapping(value = "siadap/evaluations/{id}/interim-feedback")
  @Operation(
    summary = "Save SIADAP interim feedback",
    description = "Salva os dados da ficha de feedback intercalar de uma avaliação.",
    responses = {
      @ApiResponse(
          responseCode = "200",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(implementation = SiadapInterimFeedbackDTO.class, type = "object")
          )
      )
    }
  )
  public ResponseEntity<SiadapInterimFeedbackDTO> saveInterimFeedback(
    @PathVariable("id") String id,
    @Valid @RequestBody SiadapInterimFeedbackDTO body)
  {
    final var command = new SaveSiadapInterimFeedbackCommand(id, body);
    return commandBus.send(command);
  }

  @PostMapping(value = "siadap/evaluations/{id}/interim-feedback/revisions/{revisionId}/propose")
  @Operation(
    summary = "Propose an objective revision",
    description = "Avaliador propõe formalmente uma revisão de objetivo."
  )
  public ResponseEntity<SiadapInterimFeedbackDTO> proposeObjectiveRevision(
    @PathVariable("id") String id,
    @PathVariable("revisionId") String revisionId)
  {
    return commandBus.send(new ProposeObjectiveRevisionCommand(id, revisionId));
  }

  @PostMapping(value = "siadap/evaluations/{id}/interim-feedback/revisions/{revisionId}/accept")
  @Operation(
    summary = "Accept an objective revision",
    description = "Avaliado aceita a revisão proposta; o objetivo revisto passa a ser o de referência (RECONC-04)."
  )
  public ResponseEntity<SiadapInterimFeedbackDTO> acceptObjectiveRevision(
    @PathVariable("id") String id,
    @PathVariable("revisionId") String revisionId)
  {
    return commandBus.send(new AcceptObjectiveRevisionCommand(id, revisionId));
  }

  @PostMapping(value = "siadap/evaluations/{id}/interim-feedback/revisions/{revisionId}/negotiate")
  @Operation(
    summary = "Negotiate an objective revision",
    description = "Avaliado solicita negociação da revisão proposta."
  )
  public ResponseEntity<SiadapInterimFeedbackDTO> negotiateObjectiveRevision(
    @PathVariable("id") String id,
    @PathVariable("revisionId") String revisionId,
    @Valid @RequestBody NegotiateObjectiveRevisionRequestDTO body)
  {
    return commandBus.send(new NegotiateObjectiveRevisionCommand(id, revisionId, body));
  }
}
